### ISSUE TITLE
你好 请问一下assets里的模型文件格式是如何生成的？

### ISSUE THREAD

**Issue by axdo** [JiweiMaster/MobileDetBenchmark#4]
你好 我尝试直接将训练好的模型的pdparams格式后缀直接改为param 这样的做法是无效的，但是文档里没有找到修改方法，请问能告诉一下下吗 ？ 非常感谢了

**Comment by JiweiMaster** [comment]
param是ncnn的参数文件，你需要将paddle的模型转换成onnx,然后将onnx转换成ncnn的模型就可以了，具体的方法可以先参考PaddleDetection将paddle的模型转换成onnx，然后参考ncnn，将onnx转换成ncnn的param的文件(https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/third_engine/demo_ncnn)

**Comment by axdo** [comment]
> param是ncnn的参数文件，你需要将paddle的模型转换成onnx,然后将onnx转换成ncnn的模型就可以了，具体的方法可以先参考PaddleDetection将paddle的模型转换成onnx，然后参考ncnn，将onnx转换成ncnn的param的文件(https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/third_engine/demo_ncnn)

你好 感谢您的回答 我转换完成后 放入程序 点击run提示unknown shape 然后我根据其他的把Input那块的image改成了data 好像是能出结果了 我想问一下 如果想在我的数据集上验证 应该改哪个地方？这个没有找到

**Comment by axdo** [comment]
> param是ncnn的参数文件，你需要将paddle的模型转换成onnx,然后将onnx转换成ncnn的模型就可以了，具体的方法可以先参考PaddleDetection将paddle的模型转换成onnx，然后参考ncnn，将onnx转换成ncnn的param的文件(https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/third_engine/demo_ncnn)

你好 感谢您的回答 我转换完成后 放入程序 点击run提示unknown shape 然后我根据其他的把Input那块的image改成了data 好像是能出结果了 我想问一下 如果想在我的数据集上验证 应该改哪个地方？这个没有找到
